FROM python:3.12-slim

WORKDIR /app

COPY requirements-sim.txt .
RUN pip install --no-cache-dir -r requirements-sim.txt

COPY src/settings.py ./src/settings.py

COPY simulator/opcua_server.py .

CMD ["python3", "opcua_server.py"]
