# ==========================================
# AGENT
# ==========================================
[agent]
  interval        = "100ms"
  flush_interval  = "2s"
  flush_jitter    = "500ms"
  metric_batch_size   = 100000
  metric_buffer_limit = 1000000

  omit_hostname = true

# ==========================================
# OUTPUT
# ==========================================
[[outputs.influxdb_v2]]
  urls         = ["http://influxdb:8086"]
  token        = "$INFLUX_TOKEN"
  organization = "mi_fabrica"
  bucket       = "telemetria"
  timeout      = "30s"

# ==========================================
# INPUT: Telemetría de sensores
# ==========================================
[[inputs.mqtt_consumer]]
  servers      = ["tcp://mosquitto:1883"]
  topics       = ["gateway/data/#"]
  data_format  = "json_v2"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "sensor_data"
    timestamp_path   = "timestamp"
    timestamp_format = "RFC3339"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "value"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "quality"
      type = "string"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "sensor_id"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "unit"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "quality"

# ==========================================
# INPUT: Alertas de anomalías
# ==========================================
[[inputs.mqtt_consumer]]
  servers     = ["tcp://mosquitto:1883"]
  topics      = ["gateway/alerts"]
  data_format = "json_v2"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "anomaly_alerts"
    timestamp_path   = "timestamp"
    timestamp_format = "RFC3339"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "value"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "mean"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "std"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "threshold"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "duration_samples"
      type = "int"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "sensor_id"
    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "type"

# ==========================================
# INPUT: Eventos de vuelta
# ==========================================
[[inputs.mqtt_consumer]]
  servers     = ["tcp://mosquitto:1883"]
  topics      = ["gateway/laps"]
  data_format = "json_v2"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "lap_events"
    timestamp_path   = "timestamp"
    timestamp_format = "RFC3339"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "lap_time_ms"
      type = "int"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "lap_number"
      type = "int"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "session_id"
      type = "string"
